// example/vue3/src/components/ValidateStorageAvailable.vue
<template>
  <div class="validate-storage-avaiable">
    <div class="card">
      <div class="line-1">
        <p>是否支持localStorage：{{ isLocalStorageAvaiable }}</p>
        <button @click="handleCheckLocalClick">检测</button>
      </div>
      <div class="line-2">
        <p>是否支持localStorage：{{ isSessionStorageAvaiable }}</p>
        <button @click="handleCheckSessionClick">检测</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { validateStorageAvailable, StroageType } from '@dinofe/xt-core/web'
import { delay } from '@dinofe/xt-core/common';

const isLocalStorageAvaiable = ref<string | boolean>('检测中')
const isSessionStorageAvaiable = ref<string | boolean>('检测中')

const handleCheckLocalClick = async () => {
  isLocalStorageAvaiable.value = '检测中'
  await delay(1000)
  isLocalStorageAvaiable.value = validateStorageAvailable(StroageType.localStorage)
}

const handleCheckSessionClick = async () => {
  isSessionStorageAvaiable.value = '检测中'
  await delay(1000)
  isSessionStorageAvaiable.value = validateStorageAvailable(StroageType.sessionStorage)
}

onMounted(() => {
  handleCheckLocalClick()
  handleCheckSessionClick()
})
</script>

<style scoped></style>

// example/react/src/components/ValidateStorageAvailable.jsx
import { delay } from "@dinofe/xt-core/common"
import { validateStorageAvailable, StroageType } from "@dinofe/xt-core/web"
import { useEffect, useState } from "react"

function ValidateStorageAvailable() {
  const [isLocalStorageAvaiable, setIsLocalStorageAvaiable] = useState('检测中')
  const [isSessionStorageAvaiable, setIsSessionStorageAvaiable] = useState('检测中')

  const handleCheckLocalClick = async () => {
    setIsLocalStorageAvaiable('检测中')
    await delay(1000)
    setIsLocalStorageAvaiable(validateStorageAvailable(StroageType.localStorage))
  }
  
  const handleCheckSessionClick = async () => {
    setIsSessionStorageAvaiable('检测中')
    await delay(1000)
    setIsSessionStorageAvaiable(validateStorageAvailable(StroageType.sessionStorage))
  }

  useEffect(() => {
    handleCheckLocalClick()
    handleCheckSessionClick()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <div className="validate-storage-avaiable">
      <div className="card">
        <div className="line-1">
          <p>是否支持localStorage：{ isLocalStorageAvaiable + '' }</p>
          <button onClick={handleCheckLocalClick}>检测</button>
        </div>
        <div className="line-2">
          <p>是否支持localStorage：{ isSessionStorageAvaiable + '' }</p>
          <button onClick={handleCheckSessionClick}>检测</button>
        </div>
      </div>
    </div>
  )
}

export default ValidateStorageAvailable
