// example/vue2/src/components/ValidateStorageAvailable.vue
<template>
  <div class="validate-storage-avaiable">
    <div class="card">
      <div class="line-1">
        <p>是否支持localStorage：{{ isLocalStorageAvaiable }}</p>
        <button @click="handleCheckLocalClick">检测</button>
      </div>
      <div class="line-2">
        <p>是否支持localStorage：{{ isSessionStorageAvaiable }}</p>
        <button @click="handleCheckSessionClick">检测</button>
      </div>
    </div>
  </div>
</template>

<script>
import { validateStorageAvailable, StroageType } from '@dinofe/xt-core/web'
import { delay } from '@dinofe/xt-core/common'

export default {
  name: 'ValidateStorageAvailable',
  data () {
    return {
      isLocalStorageAvaiable: '检测中',
      isSessionStorageAvaiable: '检测中'
    }
  },
  methods: {
    async handleCheckLocalClick () {
      this.isLocalStorageAvaiable = '检测中'
      await delay(1000)
      this.isLocalStorageAvaiable = validateStorageAvailable(StroageType.localStorage)
    },
    async handleCheckSessionClick () {
      this.isSessionStorageAvaiable = '检测中'
      await delay(1000)
      this.isSessionStorageAvaiable = validateStorageAvailable(StroageType.sessionStorage)
    }
  },
  mounted () {
    this.handleCheckLocalClick()
    this.handleCheckSessionClick()
  }
}
</script>

<style scoped></style>

// example/react/src/components/ValidateStorageAvailable.jsx
import { delay } from "@dinofe/xt-core/common"
import { validateStorageAvailable, StroageType } from "@dinofe/xt-core/web"
import { useEffect, useState } from "react"

function ValidateStorageAvailable() {
  const [isLocalStorageAvaiable, setIsLocalStorageAvaiable] = useState('检测中')
  const [isSessionStorageAvaiable, setIsSessionStorageAvaiable] = useState('检测中')

  const handleCheckLocalClick = async () => {
    setIsLocalStorageAvaiable('检测中')
    await delay(1000)
    setIsLocalStorageAvaiable(validateStorageAvailable(StroageType.localStorage))
  }
  
  const handleCheckSessionClick = async () => {
    setIsSessionStorageAvaiable('检测中')
    await delay(1000)
    setIsSessionStorageAvaiable(validateStorageAvailable(StroageType.sessionStorage))
  }

  useEffect(() => {
    handleCheckLocalClick()
    handleCheckSessionClick()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <div className="validate-storage-avaiable">
      <div className="card">
        <div className="line-1">
          <p>是否支持localStorage：{ isLocalStorageAvaiable + '' }</p>
          <button onClick={handleCheckLocalClick}>检测</button>
        </div>
        <div className="line-2">
          <p>是否支持localStorage：{ isSessionStorageAvaiable + '' }</p>
          <button onClick={handleCheckSessionClick}>检测</button>
        </div>
      </div>
    </div>
  )
}

export default ValidateStorageAvailable
